---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	classify(classify)
	rag(rag)
	escalate(escalate)
	unknown(unknown)
	__end__([<p>__end__</p>]):::last
	__start__ --> classify;
	escalate --> __end__;
	rag --> __end__;
	unknown --> __end__;
	classify -.-> rag;
	classify -.-> escalate;
	classify -.-> unknown;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
